[package]
name = "xeval"
version = "0.1.0"
edition = "2024"
description = "LLM evaluation framework"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/xeval"

[[bin]]
name = "xeval"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
config = "0.15.15"
dialoguer = "0.12.0"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
toml = { version = "0.8.19", features = ["parse", "display"] }
xeval_project = { path = "../project" }
xeval_global = { path = "../global" }
xeval_openai = { path = "../openai" }
tokio = { version = "1.40.0", features = ["rt-multi-thread", "macros"] }
console = "0.16.0"
indicatif = { version = "0.18.0", features = ["tokio"] }
xeval_files = { path = "../files" }
xeval_types = { path = "../types" }
sha2 = "0.10.8"
serde_json = "1.0.132"
