[package]
name = "xeval_global"
version = "0.1.0"
edition = "2024"
description = "xeval global state crate"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/xeval"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
config = "0.15.15"
dialoguer = "0.12.0"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"
toml = { version = "0.8.19", features = ["parse", "display"] }
dirs = "5.0.1"
toml_edit = "0.23.4"
