[package]
name = "xeval_types"
version = "0.1.0"
edition = "2024"
description = "xeval: simple eval spec and conversions"
authors = ["Sasha Koss <koss@nocorp.me>"]
license = "MIT"
repository = "https://github.com/kossnocorp/xeval"

[dependencies]
anyhow = "1.0.99"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.132"
regex = "1.11.1"
ordered-float = { version = "5.0.0", features = ["serde"] }
once_cell = "1.19.0"
xeval_openai = { version = "0.1.0", path = "../openai" }

[dev-dependencies]
insta = { version = "1.41.1", features = ["yaml"] }
pretty_assertions = "1.4.1"
serde_yaml = "0.9.34+deprecated"
